Wyświetl tabliczkę mnożenia 10 x 10 w następującej formie:
1 2 3 4 …
2 4 6 8 …
3 6 9 12 …
4 8 12 16 …
…

Requirements:
. Program powinien wyświetlać tekst.
. Wyświetlony tekst powinien składać się z 10 linii.
. Każdy wyświetlony ciąg musi zawierać 10 liczb rozdzielonych spacjami.
